// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCA11FuEWz9yNBLCbvidB7gCtPlLXijVEo',
    appId: '1:828283289351:android:3496867e340530195ccfa2',
    messagingSenderId: '828283289351',
    projectId: 'alarmate-8e25a',
    databaseURL: 'https://alarmate-8e25a-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'alarmate-8e25a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCT-TsiK-ul5jfdNuud2QaEoFKW6yEMgfE',
    appId: '1:828283289351:ios:a0e283d7c6a9fc2c5ccfa2',
    messagingSenderId: '828283289351',
    projectId: 'alarmate-8e25a',
    databaseURL: 'https://alarmate-8e25a-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'alarmate-8e25a.firebasestorage.app',
    androidClientId: '828283289351-lq0j05jh2c2d5jg5ehdogmlc38dpq0bi.apps.googleusercontent.com',
    iosClientId: '828283289351-2a385kak05sule7d5kb7pqr1unaj0h6p.apps.googleusercontent.com',
    iosBundleId: 'com.bekircaglar.alarmate',
  );

}